imports:
    - { resource: security.yaml }

knpu_oauth2_client:
    clients:
        keycloak:
            type: generic
            provider_class: IDCI\Bundle\KeycloakSecurityBundle\Provider\Keycloak
            client_id: "%keycloak_client_id%"
            client_secret: "%keycloak_client_secret%"
            redirect_route: idci_security_auth_connect_check_keycloak
            redirect_params: {}
            provider_options:
                auth_server_url: "%keycloak_server_url%"
                realm: "%keycloak_realm%"
                # Optional: Encryption algorith, i.e. RS256
                # encryption_algorithm: ''
                # Optional: Encryption key path, i.e. ../key.pem
                # encryption_key_path: ''
                # Optional: Encryption key, i.e. contents of key or certificate
                # encryption_key: ''
                # whether to check OAuth2 "state": defaults to true
                # use_state: true
