idci_security_auth_connect_keycloak:
    path: /auth/connect/keycloak
    defaults: { _controller: IDCIKeycloakSecurityBundle:Keycloak:connect }

idci_security_auth_connect_check_keycloak:
    path: /auth/connect-check/keycloak
    defaults: { _controller: IDCIKeycloakSecurityBundle:Keycloak:connectCheck }

idci_security_auth_logout:
    path: /auth/logout
    defaults: { _controller: IDCIKeycloakSecurityBundle:Keycloak:logout }
