nti_security_auth_connect_keycloak:
    path:       /auth/connect/keycloak
    controller: NTI\KeycloakSecurityBundle\Controller\KeycloakController::connectAction

nti_security_auth_connect_check_keycloak:
    path:       /auth/connect-check/keycloak
    controller: NTI\KeycloakSecurityBundle\Controller\KeycloakController::connectCheckAction

nti_security_auth_logout:
    path:       /auth/logout
    controller: NTI\KeycloakSecurityBundle\Controller\KeycloakController::logoutAction

nti_keycloak_admin:
    resource: "@KeycloakSecurityBundle/Controller/"
    type:     annotation
    prefix: /keycloak/admin
