nti_keycloak_admin:
    resource: "@KeycloakSecurityBundle/Controller/Admin"
    type:     annotation
    prefix: /keycloak/admin

nti_keycloak_api_admin:
    resource: "@KeycloakSecurityBundle/Controller/ApiAdmin"
    type:     annotation
    prefix: /api/keycloak/admin
