security:
    providers:
        nti_keycloak_security_provider:
            id: NTI\KeycloakSecurityBundle\Security\User\KeycloakUserProvider
        nti_keycloak_bearer_security_provider:
            id: NTI\KeycloakSecurityBundle\Security\User\KeycloakBearerUserProvider
