security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        #tms_digifid_memory_users:
            memory:
        #        users: '%tms_digifid_users%'

        #tms_digifid_oauth_users:
            id: idci_keycloak.user_provider.oauth
