services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    IDCI\Bundle\KeycloakSecurityBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'
