services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    NTI\KeycloakSecurityBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests,Provider/KeycloakResourceOwner.php}'

    NTI\KeycloakSecurityBundle\Controller\KeycloakController:
        public: true
        bind:
            $defaultTargetPath: '%nti_keycloak_security.default_target_path%'
        tags: ['controller.service_arguments']

    NTI\KeycloakSecurityBundle\Security\Authenticator\KeycloakAuthenticator:

    NTI\KeycloakSecurityBundle\Security\User\KeycloakUserProvider:
        tags:
            - { name: nti_keycloak_security.user_provider, alias: oauth }

    NTI\KeycloakSecurityBundle\Security\User\KeycloakBearerUserProvider:
        arguments:
            $sslVerification: '%nti_keycloak_security.ssl_verification%'

    NTI\KeycloakSecurityBundle\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    nti.keycloak.admin.user.service:
        public: true
        class: NTI\KeycloakSecurityBundle\Service\KeycloakAdminUserService
        arguments: ["@service_container"]

    nti.keycloak.admin.role.service:
        public: true
        class: NTI\KeycloakSecurityBundle\Service\KeycloakAdminRoleService
        arguments: ["@service_container"]